import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { Activity, Bell, Check, ChevronRight, Cloud, Gauge, History, LayoutDashboard, LogOut, Map, Menu, Radio, Save, Settings, ShieldAlert, Thermometer, UserRound, X, Zap } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { createAlerts, createHistory, createReading, createScenarioEvent } from './demo/simulator'
import { login, loginWithGoogle, logout, observeAuth, register, resetPassword } from './services/auth'
import { observeCurrentStatus, observeRecentAlerts, observeRecentEvents, observeRecentReadings } from './services/firestore'
import { calculateRisk } from './utils/riskEngine'
import { DEFAULT_RISK_CONFIG, type Alert, type DemoScenario, type RiskConfig, type SensorReading, type TimelineEvent } from './types/slopeShield'
import './App.css'

type FirebaseUser = import('firebase/auth').User
const demoScenarios: DemoScenario[] = ['stable', 'moisture', 'movement', 'tilt', 'rain', 'danger']

function App() {
  const firebaseReady = Boolean(import.meta.env.VITE_FIREBASE_API_KEY)
  const [user, setUser] = useState<FirebaseUser | null>(null)
  const [authLoading, setAuthLoading] = useState(firebaseReady)
  useEffect(() => firebaseReady ? observeAuth((next) => { setUser(next); setAuthLoading(false) }) : undefined, [firebaseReady])
  if (authLoading) return <AuthLoading />
  if (firebaseReady && !user) return <AuthScreen />
  return <BrowserRouter><ProtectedApp user={user} /></BrowserRouter>
}
function AuthLoading() { return <div className="auth-screen"><div className="auth-panel"><div className="brand-mark"><ShieldAlert size={22} /></div><h1>Loading secure session</h1><p>Connecting to Firebase Authentication.</p></div></div> }
function AuthScreen() {
  const [registerMode, setRegisterMode] = useState(false); const [forgot, setForgot] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); try { if (forgot) { await resetPassword(email); setMessage('Password reset email sent.') } else if (registerMode) await register(email, password); else await login(email, password) } catch (error) { setMessage(error instanceof Error ? error.message.replace('Firebase: Error (auth/', '').replace(').', '') : 'Authentication failed.') } }
  return <div className="auth-screen"><div className="auth-panel"><div className="brand-mark"><ShieldAlert size={22} /></div><p className="eyebrow">SECURE MONITORING ACCESS</p><h1>{forgot ? 'Reset your password' : registerMode ? 'Create operator account' : 'Welcome to SlopeShield'}</h1><p className="auth-copy">Access is required for live Firebase monitoring and alert history.</p>{message && <div className="notice warning">{message}</div>}{!forgot && <button className="google-button" onClick={() => loginWithGoogle().catch((error) => setMessage(error.message))}>Continue with Google</button>}<form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label>{!forgot && <label>Password<input type="password" minLength={6} required value={password} onChange={(event) => setPassword(event.target.value)} /></label>}<button className="primary-button" type="submit">{forgot ? 'Send reset email' : registerMode ? 'Create account' : 'Sign in'}</button></form><div className="auth-links">{!forgot && <button onClick={() => setForgot(true)}>Forgot password?</button>}<button onClick={() => { setForgot(false); setRegisterMode(!registerMode) }}>{registerMode ? 'Already registered? Sign in' : 'Create an account'}</button>{forgot && <button onClick={() => setForgot(false)}>Back to sign in</button>}</div></div></div>
}
function ProtectedApp({ user }: { user: FirebaseUser | null }) {
  const [mode, setMode] = useState<'demo' | 'live'>('demo'); const [scenario, setScenario] = useState<DemoScenario>('stable'); const [reading, setReading] = useState(() => createReading('stable')); const [history, setHistory] = useState(() => createHistory('stable')); const [events, setEvents] = useState<TimelineEvent[]>(() => [createScenarioEvent('stable')]); const [alerts, setAlerts] = useState<Alert[]>(() => createAlerts('stable')); const [config, setConfig] = useState<RiskConfig>(DEFAULT_RISK_CONFIG); const [menuOpen, setMenuOpen] = useState(false)
  const location = useLocation(); const liveUnavailable = mode === 'live' && !import.meta.env.VITE_FIREBASE_API_KEY
  useEffect(() => { if (mode !== 'live') return; const unsubs = [observeCurrentStatus((next) => next && setReading(next), () => undefined), observeRecentReadings(setHistory, () => undefined), observeRecentEvents(setEvents, () => undefined), observeRecentAlerts(setAlerts, () => undefined)]; return () => unsubs.forEach((unsubscribe) => unsubscribe()) }, [mode])
  useEffect(() => { if (mode !== 'demo') return; const timer = window.setInterval(() => { const next = { ...createReading(scenario), timestamp: Date.now() }; setReading(next); setHistory((current) => [...current.slice(-47), next]); setAlerts((current) => [...createAlerts(scenario), ...current].slice(0, 20)) }, 5000); return () => window.clearInterval(timer) }, [mode, scenario])
  const selectScenario = (next: DemoScenario) => { setScenario(next); const nextReading = createReading(next); setReading(nextReading); setHistory((current) => [...current.slice(-47), nextReading]); setEvents((current) => [createScenarioEvent(next), ...current].slice(0, 50)); setAlerts((current) => [...createAlerts(next), ...current].slice(0, 20)) }
  const navItems = [{ to: '/', label: 'Monitoring center', icon: LayoutDashboard }, { to: '/risk', label: 'Risk analysis', icon: Gauge }, { to: '/sensors', label: 'Sensor monitoring', icon: Radio }, { to: '/history', label: 'Historical data', icon: History }, { to: '/alerts', label: 'Alerts', icon: Bell }, { to: '/architecture', label: 'System architecture', icon: Map }]; const titles: Record<string, string> = { '/': 'Monitoring center', '/risk': 'Risk analysis', '/sensors': 'Sensor monitoring', '/history': 'Historical data', '/alerts': 'Alerts', '/architecture': 'System architecture', '/settings': 'System settings', '/profile': 'User profile' }
  return <div className="app-shell"><aside className={`sidebar ${menuOpen ? 'sidebar-open' : ''}`}><div className="brand"><div className="brand-mark"><ShieldAlert size={21} /></div><div><strong>SlopeShield</strong><span>Monitoring center</span></div><button className="icon-button close-menu" onClick={() => setMenuOpen(false)} aria-label="Close menu"><X size={18} /></button></div><div className={`mode-banner ${mode === 'live' ? 'live-banner' : ''}`}><span className="pulse-dot" /> {mode.toUpperCase()} MODE <small>{mode === 'demo' ? 'Presenter simulation' : 'Firebase realtime source'}</small></div><nav>{navItems.map(({ to, label, icon: Icon }) => <Link key={to} to={to} className={location.pathname === to ? 'nav-item active' : 'nav-item'} onClick={() => setMenuOpen(false)}><Icon size={18} />{label}</Link>)}</nav><div className="sidebar-bottom"><Link to="/settings" className="nav-item"><Settings size={18} />System settings</Link><Link to="/profile" className="user-row"><div className="avatar">{initials(user?.displayName || user?.email || 'Demo operator')}</div><div><strong>{user?.displayName || user?.email || 'Demo operator'}</strong><span>Project operator</span></div><UserRound size={16} /></Link></div></aside><main className="main-content"><header className="topbar"><button className="icon-button menu-toggle" onClick={() => setMenuOpen(true)} aria-label="Open menu"><Menu size={21} /></button><div><p className="eyebrow">SLOPESHIELD MONITORING CENTER</p><h1>{titles[location.pathname] || 'Monitoring center'}</h1></div><div className="topbar-actions"><div className={`connection ${liveUnavailable ? 'offline' : ''}`}><span className="online-dot" />{liveUnavailable ? 'Live setup needed' : mode === 'demo' ? 'Demo stream active' : 'Firebase live'}</div><div className="avatar avatar-top">{initials(user?.displayName || user?.email || 'Demo operator')}</div></div></header><section className="content-wrap">{liveUnavailable && <div className="notice warning"><Cloud size={17} /> Live Mode needs Firebase environment variables. Demo data is never shown as live data.</div>}<Routes><Route path="/" element={<Overview reading={reading} events={events} scenario={scenario} onScenario={selectScenario} />} /><Route path="/risk" element={<RiskPage reading={reading} history={history} config={config} />} /><Route path="/sensors" element={<SensorsPage reading={reading} mode={mode} />} /><Route path="/history" element={<HistoryPage history={history} />} /><Route path="/alerts" element={<AlertsPage alerts={alerts} onAcknowledge={(id) => setAlerts((current) => current.map((alert) => alert.id === id ? { ...alert, acknowledged: true } : alert))} />} /><Route path="/architecture" element={<ArchitecturePage />} /><Route path="/settings" element={<SettingsPage mode={mode} setMode={setMode} config={config} setConfig={setConfig} />} /><Route path="/profile" element={<ProfilePage user={user} />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></section></main></div>
}
function Overview({ reading, events, scenario, onScenario }: { reading: SensorReading; events: TimelineEvent[]; scenario: DemoScenario; onScenario: (next: DemoScenario) => void }) { return <><PageIntro eyebrow="FIELD NODE / RIDGE A" title="Good morning, operator." copy="A clear read on the physical model, updated continuously." /><div className="scenario-strip"><span>Scenario</span>{demoScenarios.map((item) => <button key={item} className={scenario === item ? 'scenario active' : 'scenario'} onClick={() => onScenario(item)}>{item}</button>)}</div><div className="metric-grid"><Metric title="Risk score" value={`${reading.riskScore}`} suffix="/ 100" tone={reading.riskLevel.toLowerCase()} /><Metric title="Slope displacement" value={reading.displacement.toFixed(1)} suffix="mm" /><Metric title="Soil moisture" value={`${reading.soilMoisture}`} suffix="%" /><Metric title="Recent events" value={`${events.length}`} suffix="events" /></div><SectionTitle eyebrow="LIVE READOUT" title="System outputs" link="/sensors" linkText="View sensors" /><div className="panel output-panel"><Output label="Blue status LED" state={reading.blueLED ? 'ON / SAFE' : 'OFF'} active={reading.blueLED} /><Output label="Yellow warning LED" state={reading.yellowLED ? 'ON / WATCH' : 'OFF'} active={reading.yellowLED} /><Output label="Red danger LED" state={reading.redLED ? 'ON / DANGER' : 'OFF'} active={reading.redLED} danger /><Output label="Servo barrier" state={reading.barrierStatus} active={reading.barrierStatus === 'DEPLOYED'} danger /></div><SectionTitle eyebrow="EVENT STREAM" title="Recent activity" link="/alerts" linkText="All alerts" /><div className="panel event-list">{events.slice(0, 5).map((event) => <div className="event-row" key={event.id}><span className={`event-dot ${event.severity.toLowerCase()}`} /><div><strong>{event.type}</strong><p>{event.description}</p></div><time>{formatTime(event.timestamp)}</time></div>)}</div></> }
function RiskPage({ reading, history, config }: { reading: SensorReading; history: SensorReading[]; config: RiskConfig }) { const risk = calculateRisk(reading, config); return <><PageIntro eyebrow="DECISION SUPPORT" title="Risk analysis" copy="A transparent view of the configurable prototype scoring model." /><div className="risk-hero"><div><p className="eyebrow">CURRENT PROTOTYPE SCORE</p><strong className={`big-score ${reading.riskLevel.toLowerCase()}`}>{reading.riskScore}</strong><span className="score-denom">/100</span><h2>{reading.riskLevel}</h2><p>{risk.explanation}</p></div><Chart title="Risk trend" data={history} dataKey="riskScore" color="#167d6a" /></div><div className="two-col"><div className="panel"><div className="panel-heading"><h2>Parameter contribution</h2><span>points</span></div>{risk.contributions.map((item) => <div className="contribution" key={item.label}><div><span>{item.label}</span><strong>{item.score} / {item.maximum}</strong></div><div className="progress"><i style={{ width: `${(item.score / item.maximum) * 100}%` }} /></div></div>)}</div><div className="panel disclaimer"><ShieldAlert size={20} /><h2>Prototype parameters</h2><p>Thresholds and weights are demonstration settings for a controlled model. They are not scientifically validated landslide prediction thresholds and must not be used for real-world safety decisions.</p><Link to="/settings" className="text-link">Review configuration <ChevronRight size={15} /></Link></div></div></> }
function SensorsPage({ reading, mode }: { reading: SensorReading; mode: 'demo' | 'live' }) { const sensors = [{ icon: <Activity />, name: 'Ultrasonic distance', value: `${reading.distance.toFixed(1)} cm`, detail: `Displacement ${reading.displacement.toFixed(1)} mm`, available: true }, { icon: <Zap />, name: 'Tilt detection', value: reading.tiltDetected ? 'Movement detected' : 'Stable', detail: 'Digital tilt switch', available: true }, { icon: <Thermometer />, name: 'Soil moisture', value: mode === 'live' ? 'NOT CONNECTED' : `${reading.soilMoisture}%`, detail: mode === 'live' ? 'Awaiting physical sensor' : 'Simulated capacity', available: mode === 'demo' }, { icon: <Cloud />, name: 'Rain / water conditions', value: mode === 'live' ? 'NOT CONNECTED' : reading.rainfallLevel, detail: mode === 'live' ? 'Awaiting physical sensor' : 'Simulated condition', available: mode === 'demo' }]; return <><PageIntro eyebrow="INPUT LAYER" title="Sensor monitoring" copy="Each input is shown with its availability, current value, and last reading timestamp." /><div className="sensor-grid detailed">{sensors.map((sensor) => <article className="sensor-card" key={sensor.name}><div className="card-top"><div className="sensor-icon">{sensor.icon}</div><span className={`status ${sensor.available ? '' : 'unavailable'}`}><span />{sensor.available ? 'AVAILABLE' : 'NOT CONNECTED'}</span></div><p className="label">{sensor.name}</p><h3>{sensor.value}</h3><p className="detail">{sensor.detail}</p><p className="last-update">Last update {formatTime(reading.timestamp)}</p></article>)}</div><div className="notice"><Radio size={17} /> Live mode intentionally reports missing physical sensors as unavailable instead of inventing telemetry.</div></> }
function HistoryPage({ history }: { history: SensorReading[] }) { const [range, setRange] = useState('24h'); const [now] = useState(() => Date.now()); const data = useMemo(() => history.filter((item) => range === 'week' ? item.timestamp >= now - 7 * 86400000 : range === '24h' ? item.timestamp >= now - 86400000 : item.timestamp >= now - 3600000), [history, range, now]); return <><PageIntro eyebrow="TIME SERIES" title="Historical data" copy="Compare sensor movement, environmental conditions, and the resulting prototype score." /><div className="range-tabs">{[['hour', 'Last hour'], ['24h', 'Last 24 hours'], ['week', 'Last week'], ['custom', 'Custom range']].map(([key, label]) => <button className={range === key ? 'active' : ''} key={key} onClick={() => setRange(key)}>{label}</button>)}</div>{range === 'custom' && <div className="notice">Custom range controls are ready for a connected Firestore history; the demo series is bounded to its generated window.</div>}<div className="chart-grid"><Chart title="Risk score" data={data} dataKey="riskScore" color="#167d6a" /><Chart title="Distance / displacement" data={data} dataKey="displacement" color="#c47c32" /><Chart title="Soil moisture" data={data} dataKey="soilMoisture" color="#4d78a8" /><Chart title="Rain / water condition" data={data.map((item) => ({ ...item, rainfall: item.rainfallLevel === 'HIGH' ? 3 : item.rainfallLevel === 'MODERATE' ? 2 : 1 }))} dataKey="rainfall" color="#7a5c9e" /></div></> }
function Chart({ title, data, dataKey, color }: { title: string; data: Array<{ timestamp: number }>; dataKey: string; color: string }) { return <div className="panel chart-panel"><div className="panel-heading"><h2>{title}</h2><span>{data.length ? `${data.length} readings` : 'No data'}</span></div>{data.length ? <ResponsiveContainer width="100%" height={190}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="timestamp" tickFormatter={shortTime} minTickGap={30} /><YAxis width={28} /><Tooltip labelFormatter={(value) => new Date(Number(value)).toLocaleString()} /><Line type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer> : <div className="empty-state">Sensor data unavailable for this range.</div>}</div> }
function AlertsPage({ alerts, onAcknowledge }: { alerts: Alert[]; onAcknowledge: (id: string) => void }) { const [filter, setFilter] = useState('ALL'); const shown = alerts.filter((alert) => filter === 'ALL' || alert.severity === filter); return <><PageIntro eyebrow="RESPONSE QUEUE" title="Alerts" copy="Review generated events and acknowledge items that have been assessed." /><div className="range-tabs">{['ALL', 'INFO', 'WARNING', 'CRITICAL'].map((item) => <button className={filter === item ? 'active' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="panel alert-list">{shown.map((alert) => <div className={`alert-row ${alert.acknowledged ? 'acknowledged' : ''}`} key={alert.id}><span className={`severity ${alert.severity.toLowerCase()}`}>{alert.severity}</span><div><strong>{alert.title}</strong><p>{alert.description}</p><small>{alert.relatedSensor} · {formatTime(alert.timestamp)}</small></div>{alert.acknowledged ? <span className="acknowledged-label"><Check size={15} /> Acknowledged</span> : <button className="small-button" onClick={() => onAcknowledge(alert.id)}>Acknowledge</button>}</div>)}</div></> }
function ArchitecturePage() { const layers: Array<[string, string[]]> = [['INPUT LAYER', ['Ultrasonic sensor', 'Tilt switch', 'Soil moisture sensor', 'Rain / water sensor']], ['PROCESSING LAYER', ['ESP32', 'Local risk analysis']], ['LOCAL RESPONSE LAYER', ['LCD', 'LEDs', 'Buzzer', 'Servo barrier']], ['CLOUD LAYER', ['Wi-Fi', 'Secure ingestion gateway', 'Firebase']], ['APPLICATION LAYER', ['SlopeShield Monitoring Center']]]; return <><PageIntro eyebrow="SYSTEM MAP" title="System architecture" copy="A resilient path from physical inputs to local response and authenticated monitoring." /><div className="architecture-flow">{layers.map(([name, nodes], index) => <div className="architecture-layer" key={name}><p className="eyebrow">{name}</p><div>{nodes.map((node) => <span key={node}>{node}</span>)}</div>{index < layers.length - 1 && <ChevronRight className="flow-arrow" />}</div>)}</div><div className="notice"><ShieldAlert size={17} /> Local warnings continue when Wi-Fi or the secure gateway is unavailable. Cloud communication never blocks sampling or actuators.</div></> }
function SettingsPage({ mode, setMode, config, setConfig }: { mode: 'demo' | 'live'; setMode: (mode: 'demo' | 'live') => void; config: RiskConfig; setConfig: (config: RiskConfig) => void }) { const [saved, setSaved] = useState(false); const update = (key: keyof RiskConfig, value: string) => setConfig({ ...config, [key]: Number(value) }); return <><PageIntro eyebrow="CONTROL ROOM" title="System settings" copy="Tune this prototype's presentation and scoring configuration." /><div className="settings-grid"><div className="panel setting-block"><div className="panel-heading"><h2>Data source</h2><span>{mode.toUpperCase()}</span></div><div className="segmented"><button className={mode === 'demo' ? 'active' : ''} onClick={() => setMode('demo')}>Demo mode</button><button className={mode === 'live' ? 'active' : ''} onClick={() => setMode('live')}>Live mode</button></div><p className="setting-help">Live mode reads Firebase subscriptions. It does not fall back to demo values.</p></div><div className="panel setting-block"><div className="panel-heading"><h2>Prototype risk weighting</h2><span>Points</span></div>{[['movementWeight', 'Displacement'], ['moistureWeight', 'Soil moisture'], ['tiltWeight', 'Tilt'], ['rainfallWeight', 'Rain / water']].map(([key, label]) => <label className="range-input" key={key}>{label}<input type="number" min="0" max="100" value={config[key as keyof RiskConfig]} onChange={(event) => update(key as keyof RiskConfig, event.target.value)} /></label>)}<p className="setting-help">These are configurable demonstration values, not scientifically validated thresholds.</p><button className="primary-button compact" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1800) }}><Save size={15} />{saved ? 'Saved locally' : 'Save configuration'}</button></div></div></> }
function ProfilePage({ user }: { user: FirebaseUser | null }) { const navigate = useNavigate(); return <><PageIntro eyebrow="OPERATOR ACCOUNT" title="User profile" copy="Identity and session controls for this monitoring workspace." /><div className="panel profile-card"><div className="avatar large">{initials(user?.displayName || user?.email || 'Demo operator')}</div><div><p className="eyebrow">SIGNED IN AS</p><h2>{user?.displayName || user?.email || 'Demo operator'}</h2><p>{user?.email || 'Local demo session'}</p></div></div>{user && <button className="danger-button" onClick={async () => { await logout(); navigate('/') }}><LogOut size={16} /> Sign out</button>}</> }
function PageIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="page-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="subcopy">{copy}</p></div> }
function SectionTitle({ eyebrow, title, link, linkText }: { eyebrow: string; title: string; link: string; linkText: string }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><Link to={link} className="text-link">{linkText} <ChevronRight size={15} /></Link></div> }
function Metric({ title, value, suffix, tone }: { title: string; value: string; suffix: string; tone?: string }) { return <div className={`metric ${tone || ''}`}><p className="label">{title}</p><strong>{value}</strong><span>{suffix}</span></div> }
function Output({ label, state, active, danger = false }: { label: string; state: string; active: boolean; danger?: boolean }) { return <div className="output-row"><span className={`output-indicator ${active ? danger ? 'danger' : 'active' : ''}`} /><span>{label}</span><strong>{state}</strong></div> }
function initials(name: string) { return name.split(/\s|@/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase() }
function formatTime(timestamp: number) { return new Date(timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
function shortTime(timestamp: number) { return new Date(timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
export default App
